Update Gradle wrapper & Groovy version
An error that has been fixed as part of this commit.
Error: << was deprecated in Gradle 4.x and removed in Gradle 5.0
Fix: << has been replaced with doLast.

More info here:
https://docs.gradle.org/current/userguide/upgrading_version_4.html#changes_5.0